<!doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style>
    table{border-collapse:collapse;border-spacing:0;}
    td{padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
    th{;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
    </style>
</head>
<body>
<g:set var="grailsApplication" bean="grailsApplication"/>

<h1>Auto Updates Fail (${autoUpdates.size()})</h1>

<g:if test="${autoUpdates.size() > 0}">
    <table>
        <thead>
        <tr>
            <th>#</th>
            <th>Description</th>
            <th>Package</th>
            <th>Provider</th>
            <th>Curatory Group</th>
            <th>Start Time</th>
            <th>End Time</th>

        </tr>
        </thead>
        <g:each in="${autoUpdates}" var="autoUpdate" status="i">
            <tr>
                <td>
                    ${i + 1}
                </td>
                <td>
                    ${autoUpdate.description}
                    <br>
                    <br>
                    <g:set var="linkToAutoUpdateInfo" value="${grailsApplication.config.getProperty('serverUrl', String) + "resource/show/${autoUpdate.getOID()}"}"/>
                    ${linkToAutoUpdateInfo}
                </td>
                <td>
                    ${autoUpdate.pkg.name}
                    <br>
                    <br>
                    <g:set var="linkToPkg" value="${grailsApplication.config.getProperty('serverUrl', String) + "resource/show/${autoUpdate.pkg.getOID()}"}"/>
                    ${linkToPkg}
                </td>
                <td>
                    ${autoUpdate.pkg.provider?.name}
                </td>
                <td>
                     <g:each in="${autoUpdate.pkg.curatoryGroups}" var="curatoryGroupPackage">
                        ${curatoryGroupPackage.curatoryGroup.name}
                    </g:each>
                </td>
                <td>
                    ${autoUpdate.startTime}
                </td>
                <td>
                    ${autoUpdate.endTime}
                </td>
            </tr>
        </g:each>
    </table>
</g:if>
<g:else>
    No Auto Update with Fail found. Everything is right.
</g:else>
<br>
<br>

(This message was automatically generated by the we:kb system)
</body>
</html>
